### ISSUE TITLE
[FIX] 이미지 DB 저장 오류

### ISSUE THREAD

**Issue by DevinChoi** [project-dialendar/main-dialendar#56]
다음의 오류를 수정

`Error reading Sqlite table "Diary": Row too big to fit into CursorWindow requiredPos=0, totalRows=1`

`D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.main_dialendar, PID: 12087
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
        at com.example.main_dialendar.view.activity.DiaryActivity.getByteInBitmap(DiaryActivity.java:242)
        at com.example.main_dialendar.view.activity.DiaryActivity.updateRecord(DiaryActivity.java:283)
        at com.example.main_dialendar.view.activity.DiaryActivity.onBackPressed(DiaryActivity.java:184)`

**Comment by DevinChoi** [comment]
- [ ] 이미지 변경 없을 시 텍스트만 업데이트

- [ ] 너무 큰 이미지 사이즈 줄여서 DB에 저장
